baseURL: https://dataspirits2.netlify.app/
title: DataSpirits for R
theme: hugo-theme-m10c
paginate: 5
menu:
  main:
    - identifier: home
      name: Home
      url: /
    - identifier: tags
      name: Tags
      url: /tags/
params:
  author: naruse
  description: 自分用のR備忘録
  menu_item_separator: ' - '
  social:
    - name: github
      url: https://github.com/dataspirits
    - name: twitter
      url: https://twitter.com/dataspirits1
